TYPO3:
  CMS:
    Form:
      prototypes:
        standard:

          #======================
          # Defines the finisher
          #======================
          finishersDefinition:
            EmailToSystem:
              __inheritances:
                10: 'TYPO3.CMS.Form.mixins.finishersEmailMixin'
              options:
                templateRootPaths:
                  10: 'EXT:pizpalue/Resources/Private/Templates/Form/Finishers/MailToSystem/'